version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      ktor:
        patterns:
          - "io.ktor*"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.kotlinx*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
